runtime: nodejs12

entrypoint: npm run server

handlers:
# Serve all static files with url ending with a file extension
#- url: /(.*\..+)$
#  secure: always
#  static_files: build/\1
#  upload: build/(.*\..+)$
# Catch all handler to index.html
#- url: /
#  secure: always
#  static_files: build/index.html
#  upload: build/index.html
#- url: /
#  static_dir: build
- url: /.*
  secure: always
  #redirect_http_response_code: 301
  script: auto

env_variables:
  PORT: 8080

automatic_scaling:
  max_instances: 1
  min_instances: 0

